<template><div><h1 id="sh-form" tabindex="-1"><a class="header-anchor" href="#sh-form" aria-hidden="true">#</a> Sh Form</h1>
<h2 id="sh-form-1" tabindex="-1"><a class="header-anchor" href="#sh-form-1" aria-hidden="true">#</a> sh-form</h2>
<p>This helps generate and manage front end forms</p>
<p>Inputs will be autogenerated.</p>
<p>Validation from laravel backend will also be handled</p>
<h3 id="basic-example" tabindex="-1"><a class="header-anchor" href="#basic-example" aria-hidden="true">#</a> Basic Example</h3>
<h4 id="import-the-component" tabindex="-1"><a class="header-anchor" href="#import-the-component" aria-hidden="true">#</a> Import the component</h4>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> ShForm <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@iankibetsh/shframework'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h4 id="using-it" tabindex="-1"><a class="header-anchor" href="#using-it" aria-hidden="true">#</a> Using it</h4>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>sh-form</span>
<span class="token attr-name">:fields</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>[<span class="token punctuation">'</span>name<span class="token punctuation">'</span>,<span class="token punctuation">'</span>email<span class="token punctuation">'</span>,<span class="token punctuation">'</span>password<span class="token punctuation">'</span>]<span class="token punctuation">"</span></span>
<span class="token attr-name">action</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>users/add<span class="token punctuation">"</span></span>
<span class="token attr-name">:success_callback</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>userRegistered<span class="token punctuation">"</span></span>
<span class="token punctuation">/></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Above form will generate a form with 3 fields</p>
<ul>
<li>name field</li>
<li>email field</li>
<li>password field</li>
</ul>
<p>Form component will automatically set password field to be input type password</p>
<h3 id="attributes" tabindex="-1"><a class="header-anchor" href="#attributes" aria-hidden="true">#</a> Attributes</h3>
<h4 id="fields" tabindex="-1"><a class="header-anchor" href="#fields" aria-hidden="true">#</a> fields</h4>
<ul>
<li>
<p>Type: <code v-pre>array</code></p>
</li>
<li>
<p>Default: <code v-pre>none</code></p>
</li>
<li>
<p>Details:</p>
<p>These are the form files, like inputs, select etc</p>
</li>
<li>
<p>Example: <code v-pre>['name','email']</code></p>
</li>
</ul>
<h4 id="action" tabindex="-1"><a class="header-anchor" href="#action" aria-hidden="true">#</a> action</h4>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>default: <code v-pre>none</code></p>
</li>
<li>
<p>Details:</p>
<p>This is the action url to the api backend where the post request will be handled</p>
</li>
<li>
<p>Example: <code v-pre>users/add</code></p>
</li>
</ul>
<h4 id="current-data" tabindex="-1"><a class="header-anchor" href="#current-data" aria-hidden="true">#</a> current_data</h4>
<ul>
<li>
<p>Type: <code v-pre>object</code></p>
</li>
<li>
<p>Default: <code v-pre>null</code></p>
</li>
<li>
<p>Details:</p>
<p>Existing form data, used mostly when editing an item. Form fields will be
autofilled with data from this object. Key of the array is the input field</p>
</li>
<li>
<p>Example:</p>
</li>
</ul>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>:current_data="{
name: 'John Doe',
email: 'john@example.com'
}"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="success-callback" tabindex="-1"><a class="header-anchor" href="#success-callback" aria-hidden="true">#</a> success_callback</h4>
<ul>
<li>
<p>Type: <code v-pre>function/method</code></p>
</li>
<li>
<p>Default: <code v-pre>none</code></p>
</li>
<li>
<p>Details:</p>
<p>A method that will be invoked/called by the form when data is submitted successfully</p>
</li>
<li>
<p>Example: <code v-pre>:success_callback=&quot;userRegistered&quot;</code></p>
</li>
</ul>
<h4 id="fill-selects" tabindex="-1"><a class="header-anchor" href="#fill-selects" aria-hidden="true">#</a> fill_selects</h4>
<ul>
<li>Type: <code v-pre>object</code></li>
<li>Default: <code v-pre>none</code></li>
<li>Details:
Fill select element with select options, id will be used as option value and name will be option label displayed</li>
<li>Example:</li>
</ul>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>:fill_selects="{register_as:{
          data:[
            {id:'agent',name:'Agent'},
            {id:'customer',name:'Customer'},
          ]
        }}
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
