<template><div><h1 id="sh-form" tabindex="-1"><a class="header-anchor" href="#sh-form"><span>Sh Form</span></a></h1>
<p>This helps generate and manage front end forms</p>
<p>Inputs will be autogenerated.</p>
<p>Validation from laravel backend will also be handled</p>
<h2 id="basic-example" tabindex="-1"><a class="header-anchor" href="#basic-example"><span>Basic Example</span></a></h2>
<h4 id="import-the-component" tabindex="-1"><a class="header-anchor" href="#import-the-component"><span>Import the component</span></a></h4>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> ShForm <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@iankibetsh/shframework'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h4 id="using-it" tabindex="-1"><a class="header-anchor" href="#using-it"><span>Using it</span></a></h4>
<div class="language-html line-numbers-mode" data-ext="html" data-title="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>sh-form</span>
<span class="token attr-name">:fields</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>['name','email','password']<span class="token punctuation">"</span></span>
<span class="token attr-name">action</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>users/add<span class="token punctuation">"</span></span>
<span class="token attr-name">:successCallback</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>userRegistered<span class="token punctuation">"</span></span>
<span class="token punctuation">/></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Above form will generate a form with 3 fields</p>
<ul>
<li>name field</li>
<li>email field</li>
<li>password field</li>
</ul>
<p>Form component will automatically set password field to be input type password</p>
<h2 id="attributes" tabindex="-1"><a class="header-anchor" href="#attributes"><span>Attributes</span></a></h2>
<h3 id="fields" tabindex="-1"><a class="header-anchor" href="#fields"><span>fields</span></a></h3>
<ul>
<li>
<p>Type: <code v-pre>array</code></p>
</li>
<li>
<p>Default: <code v-pre>none</code></p>
</li>
<li>
<p>Details:</p>
<p>These are the form files, like inputs, select etc</p>
</li>
<li>
<p>Example: <code v-pre>['name','email']</code></p>
</li>
</ul>
<h3 id="action" tabindex="-1"><a class="header-anchor" href="#action"><span>action</span></a></h3>
<ul>
<li>
<p>Type: <code v-pre>string</code></p>
</li>
<li>
<p>default: <code v-pre>none</code></p>
</li>
<li>
<p>Details:</p>
<p>This is the action url to the api backend where the post request will be handled</p>
</li>
<li>
<p>Example: <code v-pre>users/add</code></p>
</li>
</ul>
<h3 id="current-data" tabindex="-1"><a class="header-anchor" href="#current-data"><span>current-data</span></a></h3>
<ul>
<li>
<p>Type: <code v-pre>object</code></p>
</li>
<li>
<p>Default: <code v-pre>null</code></p>
</li>
<li>
<p>Details:</p>
<p>Existing form data, used mostly when editing an item. Form fields will be
autofilled with data from this object. Key of the array is the input field</p>
</li>
<li>
<p>Example:</p>
</li>
</ul>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>:current-data="{
    email:'johnss@gmail.com'
 }"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="successcallback" tabindex="-1"><a class="header-anchor" href="#successcallback"><span>successCallback</span></a></h3>
<ul>
<li>Type: <code v-pre>function/method</code></li>
<li>Default: <code v-pre>none</code></li>
<li>Details:
A method that will be invoked/called by the form when data is submitted successfully</li>
<li>Example: <code v-pre>:success_callback=&quot;userRegistered&quot;</code></li>
</ul>
<h3 id="labels" tabindex="-1"><a class="header-anchor" href="#labels"><span>labels</span></a></h3>
<ul>
<li>Type: <code v-pre>object</code></li>
<li>Default: <code v-pre>none</code></li>
<li>Details:
An object that will hel change form field labels</li>
<li>Example:</li>
</ul>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>:labels="{
            date_created: 'Registration Date'
           }"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="fill-selects" tabindex="-1"><a class="header-anchor" href="#fill-selects"><span>fill-selects</span></a></h3>
<ul>
<li>Type: <code v-pre>object</code></li>
<li>Default: <code v-pre>none</code></li>
<li>Details:
Fill select element with select options, id will be used as option value and name will be option label displayed</li>
<li>Example 1 for defined select data:</li>
</ul>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>:fill-selects="{
    gender: {
      data: [
          {
            id: 'Male',
            name: 'Male'
          },
          {
            id: 'Female',
            name: 'Female'
          }
      ]
    }
  }"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Example 2 For getting data from api backend</li>
</ul>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>:fill-selects="{
    user_id: {
      url: 'admin/users/list?all=1'
  }"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Fill selects can also have suggestion (searchable), this will help search</li>
</ul>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>:fill-selects="{
    user_id: {
      suggests: true
      url: 'admin/users/list?all=1'
  }"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Fill selects can also have suggestion with multi select, this will help search</li>
</ul>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>:fill-selects="{
    user_id: {
      suggests: true,
      allowMultiple: true
      url: 'admin/users/list?all=1'
  }"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="customcomponent" tabindex="-1"><a class="header-anchor" href="#customcomponent"><span>customComponent</span></a></h3>
<p>This will help you add custom component as a form element instead
of using prebuilt</p>
<p>e.g</p>
<p>Import First</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> CkEditor <span class="token keyword">from</span> <span class="token string">'@/lib/components/form-components/CkEditor.vue'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Use it this way in your sh-form, key is the name of</p>
<div class="language-html line-numbers-mode" data-ext="html" data-title="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>sh-form</span>
        <span class="token attr-name">:fields</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>['mail','name']<span class="token punctuation">"</span></span>
        <span class="token attr-name">:custom-component</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{
    mail: CkEditor
      }<span class="token punctuation">"</span></span>
        <span class="token attr-name">:current-data</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{
        email: 'jack@gmail.com'
      }<span class="token punctuation">"</span></span>
        <span class="token attr-name">action</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>auth/register<span class="token punctuation">"</span></span>
<span class="token punctuation">/></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


